name: Build

on:
  push:
    branches-ignore:
      - main

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      - name: "Pull images"
        run: docker-compose pull
      - name: "Build"
        run: docker-compose run --rm -e JEKYLL_ENV=production jekyll jekyll build
